name: Alertas RSI BTCUSDT

on:
  schedule:
    - cron: "2,17,32,47 * * * *"
  workflow_dispatch:

jobs:
  rsi-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar archivos
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Ejecutar bot RSI
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python rsi_bot.py
